name: Update Gradle Wrapper

on: workflow_dispatch

jobs:
  update-gradle-wrapper:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Update Gradle Wrapper
        uses: yeikel/update-gradle-wrapper-action@b7ab23d6fa1abab02767e5aaf7077bb20f1e9486
        with:
         labels: dependencies
         distributions-base-url: "https://services.gradle.org/distributions"
